[package]
name = "plant-server"
version = "0.1.0"
authors = ["jbarszczewski <jakub.barszczewski@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
bson = "0.14.1"
chrono = "0.4.11"
mongodb = "0.10.0"
serde = { version = "1.0", features = ["derive"] }